
    create table carrot (
        id integer generated by default as identity,
        position_id integer unique,
        primary key (id)
    );

    create table figure (
        id integer generated by default as identity,
        position_id integer unique,
        score integer not null,
        stat_moves integer not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table fox (
        id integer not null,
        primary key (id)
    );

    create table position (
        id integer generated by default as identity,
        x integer not null,
        y integer not null,
        primary key (id)
    );

    create table rabbit (
        id integer not null,
        nutrition integer not null,
        primary key (id)
    );

    alter table if exists carrot 
       add constraint FKhrgdgpuv75jwgktsf9dttb3o3 
       foreign key (position_id) 
       references position;

    alter table if exists figure 
       add constraint FK5l7i6hf0pgpagd1lh4xkf82hd 
       foreign key (position_id) 
       references position;

    alter table if exists fox 
       add constraint FKfgt5adki5traw7le61erlooby 
       foreign key (id) 
       references figure;

    alter table if exists rabbit 
       add constraint FKrywoufcma1x2wnf9tmuosvtbb 
       foreign key (id) 
       references figure;
